### ISSUE TITLE
Question about the OptiLIME R^2 convert formula

### ISSUE THREAD

**Issue by singsinghai** [giorgiovisani/lime_stability#1]
Hi Giorgio Visani,

I am a Bachelor's student currently doing a thesis about LIME. I am very interested in your topics about OptiLIME and Stability Indices. 

I find these two topics very helpful and want to research more about them. However, in the [paper of OptiLIME](https://arxiv.org/abs/2006.05714), you converted $R^{2}$ function into 𝑙(𝑘𝑤, $\overset{\sim}{R^{2}}$), with the formula as below:
<img width="389" alt="image" src="https://user-images.githubusercontent.com/91768339/222973011-3f3b6857-719b-48e6-b0ae-7189ec92a732.png">

It would be pleased if I can ask you 2 questions on this:
- Why do we need to convert the $R^{2}$ function into this?
- How was the formula constructed? Can you please give more information about the math behind it?

I am very looking forward to your reply on this!

Thanks and have a good day,
Hai

**Comment by giorgiovisani** [comment]
Dear Hai,

Thanks for raising your doubts. Our goal in OptiLIME is to obtain the best value of $R^2$ for the LIME explanation of the specific unit. The reason why we use $\tilde{R}^2$ is that Stability and Adherence ($R^2$) of the explanations are antagonistic features, therefore if we maximize $R^2$ directly we would obtain $R^2$ value 1, but very bad Stability values.

So our idea was to set a predefined level of $R^2$ we want to obtain (something we can consider satisfactorily even if not exactly 1), which would also ensure higher stability values. This is precisely $\tilde{R}^2$. 

Hence we want to find the precise location of $R^2 = \tilde{R}^2$. Our idea was to compute the $R^2$ of different LIME explanations (based on the kernel width) and consider the $l$ function, which is basically the same as $R^2$ when the value is below threshold, while it reverts the values over the threshold to be under it. In this way, the $l$ function has maximum value in $\tilde{R}^2$ and we can use Bayesian Optimization to find the kernel width value corresponding to this maximum.

I hope this was useful,
Giorgio
